baseURL = 'avashraj.github.io'
languageCode = 'en-us'
title = 'putergoon.com'

enableEmoji = true

[privacy]
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true
# [params]
# 	mode="toggle"
#     custom_css = ["css/main.css"]

[params]
    katex = true
[[menu.main]]
name = "Blog"
url = "/blogs"
weight = 1

[[menu.main]]
name = "Notes"
url = "/Notes"
weight = 3

[[menu.main]]
name = "Journal"
url = "/daily"
weight = 5
